# Generated by Django 4.2 on 2024-05-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_attendance_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='section_number',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('section_number', 'name'), name='unique_section_per_course'),
        ),
    ]
