# Generated by Django 4.2 on 2024-05-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_course_section_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='timing',
            field=models.CharField(max_length=20),
        ),
    ]
